name: Export Schematic PDF
on: [push]

jobs:
  export-ecad:
    name: Export Schematic PDF
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:dev_k6
      
    steps:

    - name: Generate Short SHA Environment Variable
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      
    - name: Update system repositories, Install Required Libraries and Initialize git-lfs
      run: |
        apt update
        apt -y install git git-lfs zip librsvg2-bin imagemagick
        git lfs install
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch            

# Generate Schematic PDF

    - name: Generate Schematic PDF
      run: |
        kibot -c .github/workflows/kibot/schematic.kibot.yaml

    - name: Create Pull Request for changes
      uses: peter-evans/create-pull-request@v4      
      
    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"